"""Terraform worktree operations - extends shared worktree functionality.

This module provides Terraform-specific setup for git worktrees used in IDW workflows.
"""

import os
import subprocess
from typing import Tuple, Optional
import logging


def setup_terraform_worktree_environment(
    worktree_path: str,
    workflow_id: str,
    environment: str,
    logger: logging.Logger
) -> Tuple[bool, Optional[str]]:
    """Setup Terraform-specific worktree environment.

    This function:
    1. Creates necessary Terraform directories
    2. Generates environment-specific tfvars
    3. Sets up Terraform workspace
    4. Initializes Terraform

    Args:
        worktree_path: Path to the git worktree
        workflow_id: Unique workflow identifier
        environment: Environment name (dev, staging, prod)
        logger: Logger instance

    Returns:
        Tuple of (success, error_message)
    """
    try:
        logger.info(f"Setting up Terraform environment in worktree: {worktree_path}")

        # 1. Ensure terraform directory exists
        terraform_dir = os.path.join(worktree_path, "io/terraform")
        if not os.path.exists(terraform_dir):
            logger.error(f"Terraform directory not found: {terraform_dir}")
            return False, f"Terraform directory not found: {terraform_dir}"

        # 2. Create .terraform directory if needed
        dot_terraform = os.path.join(terraform_dir, ".terraform")
        os.makedirs(dot_terraform, exist_ok=True)

        # 3. Create environment-specific tfvars file
        tfvars_content = f"""# Auto-generated for Workflow ID: {workflow_id}
# Environment: {environment}
# Generated by IPE system

environment = "{environment}"
workflow_id = "{workflow_id}"

# Add other environment-specific variables below
"""
        tfvars_path = os.path.join(terraform_dir, f"{workflow_id}.auto.tfvars")
        with open(tfvars_path, 'w') as f:
            f.write(tfvars_content)
        logger.info(f"Created tfvars file: {tfvars_path}")

        # 4. Setup Terraform workspace (unique per workflow)
        workspace_name = f"{workflow_id}-{environment}"
        from ipe.ipe_modules.terraform_ops import setup_terraform_workspace
        success, error = setup_terraform_workspace(terraform_dir, workspace_name, logger)
        if not success:
            logger.error(f"Failed to setup workspace: {error}")
            return False, f"Workspace setup failed: {error}"

        # 5. Initialize Terraform with TFC workspace
        from ipe.ipe_modules.terraform_ops import run_terraform_init
        tfc_workspace = f"{{{{PROJECT_SLUG}}}}-{environment}"
        success, error = run_terraform_init(terraform_dir, logger, workspace=tfc_workspace)
        if not success:
            logger.error(f"Terraform init failed: {error}")
            return False, f"Terraform init failed: {error}"

        # 6. Verify setup
        logger.info("Verifying Terraform setup...")
        result = subprocess.run(
            ["terraform", "version"],
            cwd=terraform_dir,
            capture_output=True,
            text=True,
            timeout=30
        )
        if result.returncode != 0:
            return False, "Failed to verify Terraform installation"

        logger.info(f"✅ Terraform worktree environment setup complete")
        logger.info(f"   Workspace: {workspace_name}")
        logger.info(f"   Tfvars: {tfvars_path}")
        logger.info(f"   Working directory: {terraform_dir}")

        return True, None

    except Exception as e:
        logger.error(f"Failed to setup Terraform worktree: {e}")
        return False, str(e)


def cleanup_terraform_worktree(
    worktree_path: str,
    logger: logging.Logger
) -> Tuple[bool, Optional[str]]:
    """Clean up Terraform-specific worktree resources.

    This function removes Terraform workspaces and temporary files
    created during the workflow.

    Args:
        worktree_path: Path to the git worktree
        logger: Logger instance

    Returns:
        Tuple of (success, error_message)
    """
    try:
        logger.info(f"Cleaning up Terraform worktree: {worktree_path}")

        terraform_dir = os.path.join(worktree_path, "io/terraform")
        if not os.path.exists(terraform_dir):
            logger.info("No terraform directory found, skipping cleanup")
            return True, None

        # Remove auto-generated tfvars files
        for file in os.listdir(terraform_dir):
            if file.endswith(".auto.tfvars"):
                file_path = os.path.join(terraform_dir, file)
                os.remove(file_path)
                logger.info(f"Removed: {file_path}")

        # Note: We don't delete the workspace as it may contain state
        # Workspace cleanup should be done manually or via separate process

        logger.info("✅ Terraform worktree cleanup complete")
        return True, None

    except Exception as e:
        logger.error(f"Terraform worktree cleanup failed: {e}")
        return False, str(e)


def get_terraform_directory(worktree_path: str) -> str:
    """Get the terraform directory path within a worktree.

    Args:
        worktree_path: Path to the git worktree

    Returns:
        Path to terraform directory
    """
    return os.path.join(worktree_path, "io/terraform")


def validate_terraform_structure(worktree_path: str, logger: logging.Logger) -> Tuple[bool, Optional[str]]:
    """Validate that the worktree has proper Terraform structure.

    Args:
        worktree_path: Path to the git worktree
        logger: Logger instance

    Returns:
        Tuple of (success, error_message)
    """
    terraform_dir = get_terraform_directory(worktree_path)

    # Check if terraform directory exists
    if not os.path.exists(terraform_dir):
        return False, f"Terraform directory not found: {terraform_dir}"

    # Check for required files
    required_files = ["main.tf", "variables.tf"]
    missing_files = []

    for file in required_files:
        file_path = os.path.join(terraform_dir, file)
        if not os.path.exists(file_path):
            missing_files.append(file)

    if missing_files:
        return False, f"Missing required files: {', '.join(missing_files)}"

    logger.info("✅ Terraform structure validated")
    return True, None
